# Generated by Django 4.2.13 on 2024-06-09 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='')),
                ('lastname', models.CharField(max_length=50, verbose_name='')),
                ('address', models.CharField(max_length=255, verbose_name='')),
                ('zipcode', models.CharField(max_length=20, verbose_name='')),
                ('city', models.CharField(max_length=255, verbose_name='')),
                ('country', models.CharField(max_length=50, verbose_name='')),
                ('department', models.CharField(max_length=255, verbose_name='')),
                ('jobtitle', models.CharField(max_length=255, verbose_name='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
