# Generated by Django 4.2.13 on 2024-06-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='jobtitle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='zipcode',
            field=models.CharField(max_length=20),
        ),
    ]
